# Generated by Django 3.2.19 on 2023-06-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_vacancy_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='job_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('PERMANENT', 'Permanent'), ('TEMPORARY', 'Temporary'), ('APPRENTICESHIP', 'Apprenticeship'), ('VOLUNTEER', 'Volunteer')], max_length=50),
        ),
    ]
