# Generated by Django 3.2.19 on 2023-06-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_vacancy_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.IntegerField(choices=[('R', 'In review'), ('A', 'Active'), ('W', 'Withdrawn'), ('C', 'Closed')], default='R'),
        ),
    ]
