# Generated by Django 3.2.19 on 2023-06-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_vacancy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.CharField(choices=[('R', 'In review'), ('A', 'Active'), ('W', 'Withdrawn'), ('C', 'Closed')], default='R', max_length=50),
        ),
    ]
