# Generated by Django 3.2.19 on 2023-06-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_vacancy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='area',
            field=models.CharField(choices=[('DUBLIN', 'Dublin'), ('DUBLIN_CITY_CENTRE', 'Dublin City Centre'), ('DUBLIN_NORTH', 'Dublin North'), ('DUBLIN_SOUTH', 'Dublin South'), ('DUBLIN_WEST', 'Dublin West'), ('CARLOW', 'Carlow'), ('CAVAN', 'Cavan'), ('CLARE', 'Clare'), ('CORK', 'Cork'), ('DONEGAL', 'Donegal'), ('GALWAY', 'Galway'), ('KERRY', 'Kerry'), ('KILDARE', 'Kildare'), ('KILKENNY', 'Kilkenny'), ('LAOIS', 'Laois'), ('LEITRIM', 'Leitrim'), ('LIMERICK', 'Limerick'), ('LONGFORD', 'Longford'), ('LOUTH', 'Louth'), ('MAYO', 'Mayo'), ('MEATH', 'Meath'), ('MONAGHAN', 'Monaghan'), ('OFFALY', 'Offaly'), ('ROSCOMMON', 'Roscommon'), ('SLIGO', 'Sligo'), ('TIPPERARY', 'Tipperary'), ('WATERFORD', 'Waterford'), ('WESTMEATH', 'Westmeath'), ('WEXFORD', 'Wexford'), ('WICKLOW', 'Wicklow'), ('NORTHERN_IRELAND', 'Northern Ireland'), ('UK', 'UK'), ('EUROPE', 'Europe'), ('WORDLWIDE', 'Worldwide')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.CharField(choices=[('IN_REVIEW', 'In Review'), ('ACTIVE', 'Active'), ('WITHDRAWN', 'Withdrawn'), ('CLOSED', 'Closed')], default='IN_REVIEW', max_length=50),
        ),
    ]
