# Generated by Django 3.2.19 on 2023-07-04 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_alter_application_cover_letter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-applied_on'], 'verbose_name_plural': 'applications'},
        ),
        migrations.RenameField(
            model_name='application',
            old_name='applyed_on',
            new_name='applied_on',
        ),
    ]
