# Generated by Django 3.2.19 on 2023-07-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_auto_20230706_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='experience',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='experience_duration',
            field=models.CharField(choices=[('LESS_THAN_1_YEAR', 'Less than 1 year'), ('ONE_TO_2_YEARS', '1 to 2 years'), ('TWO_TO_5_YEARS', '2 to 5 years'), ('FIVE_TO_10_YEARS', '5 to 10 years'), ('MORE_THAN_10_YEARS', 'More than 10 years')], default='ONE_TO_2_YEARS', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
