# Generated by Django 3.2.19 on 2023-07-10 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_auto_20230708_0856'),
        ('jobs', '0014_auto_20230710_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='employer.employer'),
        ),
    ]
