# Generated by Django 3.2.19 on 2023-07-10 17:20

from django.db import migrations, models
import django.db.models.deletion


def populate_employer(apps, schema_editor):
    """Populate employer field in Vacancy model where it is null
    with first Employer object"""
    Vacancy = apps.get_model('jobs', 'Vacancy')
    Employer = apps.get_model('employer', 'Employer')
    for vacancy in Vacancy.objects.filter(employer__isnull=True):
        vacancy.employer = Employer.objects.first()
        vacancy.save()


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_auto_20230708_0856'),
        ('jobs', '0014_auto_20230710_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='employer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='employer.employer'),
        ),
        migrations.RunPython(populate_employer),
        migrations.AlterField(
            model_name='vacancy',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='employer.employer'),
        ),

    ]
