# Generated by Django 3.2.19 on 2023-07-07 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
        ('jobs', '0015_auto_20230706_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='employer.employer'),
        ),
    ]
