# Generated by Django 3.2.19 on 2023-07-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_vacancy_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume_snapshot',
            field=models.JSONField(default=dict),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='vacancy_snapshot',
            field=models.JSONField(default=dict),
            preserve_default=False,
        ),
    ]
