# Generated by Django 3.2.19 on 2023-07-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_alter_vacancy_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume_snapshot',
            field=models.JSONField(),
        ),
        migrations.AddField(
            model_name='application',
            name='vacancy_snapshot',
            field=models.JSONField(),
        ),
    ]
