# Generated by Django 3.2.19 on 2023-07-12 10:50

from django.db import migrations, models
import django.db.models.deletion


def populate_employer(apps, schema_editor):
    """Populate employer field in Application model where it is null
    with Vacancy's employer"""
    Application = apps.get_model('jobs', 'Application')
    for application in Application.objects.filter(employer__isnull=True):
        application.employer = application.vacancy.employer
        application.save()


def reverse_populate_employer(apps, schema_editor):
    """Reverse populate employer field in Application model"""
    Application = apps.get_model('jobs', 'Application')
    for application in Application.objects.filter(employer__isnull=False):
        application.employer = None
        application.save()


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_alter_employerprofile_company'),
        ('jobs', '0016_auto_20230710_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='employer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='employer.employer'),
        ),
        migrations.RunPython(code=populate_employer, reverse_code=reverse_populate_employer),
        migrations.AlterField(
            model_name='application',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='employer.employer'),
        ),
    ]
