# Generated by Django 3.2.19 on 2023-07-08 08:56

import cloudinary_storage.storage
from django.db import migrations, models
import jobportal.validators


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0008_alter_resume_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='cv',
            field=models.FileField(blank=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='cv/', validators=[jobportal.validators.FileValidator(content_types=('application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'), max_size=524288)]),
        ),
    ]
