# Generated by Django 3.2.19 on 2023-06-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0002_jobseekerprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='profile_placeholder', upload_to='jobseeker_avatars'),
        ),
    ]
