# Generated by Django 3.2.19 on 2023-06-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0003_alter_jobseekerprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='profile_placeholder.png', upload_to='jobseeker_avatars'),
        ),
    ]
