# Generated by Django 3.2.19 on 2023-06-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0004_alter_jobseekerprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=10, null=True),
        ),
    ]
