# Generated by Django 3.2.19 on 2023-06-25 22:53

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0005_alter_jobseekerprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='name',
            field=models.CharField(max_length=254),
        ),
    ]
