# Generated by Django 3.2.19 on 2023-06-21 20:38

from django.db import migrations, models
import jobportal.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0005_alter_jobseekerprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='profile_placeholder.png', upload_to='jobseeker_avatars', validators=[jobportal.validators.FileValidator(max_size=5242880)]),
        ),
    ]
