# Generated by Django 3.2.19 on 2023-06-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0007_alter_jobseekerprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='name',
            field=models.CharField(max_length=254),
        ),
    ]
