# Generated by Django 3.2.19 on 2023-07-03 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0007_auto_20230627_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='applications',
        ),
    ]
