# Generated by Django 3.2.19 on 2023-07-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0008_remove_jobseekerprofile_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='name',
            field=models.CharField(max_length=70),
        ),
    ]
