# Generated by Django 3.2.19 on 2023-07-05 18:39

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_remove_user_name'),
        ('resumes', '0008_alter_resume_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('employer', django.db.models.manager.Manager()),
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254)),
                ('company', models.CharField(blank=True, max_length=254)),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True, max_length=254)),
                ('bookmarkers', models.ManyToManyField(blank=True, related_name='bookmarked_by', to='resumes.Resume')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employer.employer')),
            ],
        ),
    ]
