# Generated by Django 3.2.19 on 2023-07-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0009_alter_resume_cv'),
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='bookmarkers',
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favoriters', to='resumes.Resume'),
        ),
    ]
