# Generated by Django 3.2.19 on 2023-07-10 17:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_vacancy_employer'),
        ('resumes', '0009_alter_resume_cv'),
        ('employer', '0002_auto_20230708_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('offered_on', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='employer.employer')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='resumes.resume')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='jobs.vacancy')),
            ],
            options={
                'ordering': ['-offered_on'],
            },
        ),
    ]
