# Generated by Django 3.2.19 on 2023-07-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_auto_20230710_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='name',
            field=models.CharField(max_length=70),
        ),
    ]
