# Generated by Django 3.2.19 on 2023-07-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_alter_employerprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='company',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
