# Generated by Django 3.2.19 on 2023-07-13 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_alter_employerprofile_company'),
        ('jobseeker', '0009_alter_jobseekerprofile_name'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationnotification',
            options={'ordering': ['-is_read', '-timestamp']},
        ),
        migrations.CreateModel(
            name='JobOfferNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offer_notifications', to='employer.joboffer')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offer_notifications', to='jobseeker.jobseeker')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.employer')),
            ],
            options={
                'verbose_name_plural': 'job offer notifications',
                'ordering': ['-is_read', '-timestamp'],
            },
        ),
    ]
